# Generated by Django 5.2 on 2025-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
