# Generated by Django 5.2 on 2025-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_adventure_address_adventure_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
