# Generated by Django 5.2 on 2025-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_alter_adventure_end_time_alter_adventure_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
