# Generated by Django 5.2 on 2025-04-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_adventure_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='online_booking',
            field=models.BooleanField(default=False),
        ),
    ]
