# Generated by Django 5.2 on 2025-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_adventure_online_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adventure_images/'),
        ),
    ]
